"""adiciona_campo_package_id_ao_modelo_booking

Revision ID: 370c674d33dd
Revises: 60e841d23977
Create Date: 2025-07-08 14:51:57.223308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370c674d33dd'
down_revision = '60e841d23977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_booking_package_id'), ['package_id'], unique=False)
        batch_op.create_foreign_key(None, 'package', ['package_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_booking_package_id'))
        batch_op.drop_column('package_id')

    # ### end Alembic commands ###
