"""add descricao to package

Revision ID: ecdc16598a41
Revises: de84610fab55
Create Date: 2025-07-09 20:19:33.226024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecdc16598a41'
down_revision = 'de84610fab55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_service_id'), ['service_id'], unique=False)

    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.String(length=1000), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('descricao')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_service_id'))
        batch_op.drop_index(batch_op.f('ix_booking_payment_status'))

    # ### end Alembic commands ###
