"""Adiciona campos de pagamento

Revision ID: f3ae5ab643e9
Revises: 40ca4a532bf7
Create Date: 2025-07-04 15:55:13.869307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ae5ab643e9'
down_revision = '40ca4a532bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_preference_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('total_amount')
        batch_op.drop_column('payment_preference_id')
        batch_op.drop_column('payment_id')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
